source:
  test_source:
    filepath_regex: [.*/.*.sh, .*/doc/web/man/.*.html, .*/test/.*.py]
  auto_generate_source:
    filepath_regex:
    - .*/.code.yml
    - .*/.ci/.*
  third_party_source:
    filepath_regex:
    - .*/usr/.*
    - .*/include/c++/.*
