source:
  test_source:
    filepath_regex: [.*/.*.sh, .*/doc/web/man/.*.html, .*/test/.*.py]
  auto_generate_source:
    filepath_regex:
    - .*/.code.yml
    - .*/.ci/.*
  third_party_source:
    filepath_regex:
    - .*/usr/.*
    - .*/include/c++/.*
ci:
  params:
    # 非必填，填写需要监控MR合并的target分支，list形式, 如果mr/push/tag均未配置，默认监控目标分支为master的mr合并, *匹配0~n个任意字符
    mr:
    - master
    push:
    - master
    tag:
    - '*'
    lang:
    - C_CPP
    script: |-
      echo "skip build"
    gatekeepers:
    - tegkunzhang
    image: mirrors.tencent.com/ci/tlinux3_ci:2.3.0
    enableSubmodule: false
    receivers: []
